export enum AuditEventType {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_DENIED_NOT_MEMBER = "LOGIN_DENIED_NOT_MEMBER",
  LOGIN_DENIED = "LOGIN_DENIED",
  TOKEN_REVOKED = "TOKEN_REVOKED",
  TOKEN_REFRESHED = "TOKEN_REFRESHED",
  MEMBER_LEFT_GUILD = "MEMBER_LEFT_GUILD",
  MEMBER_BANNED = "MEMBER_BANNED",
  MANUAL_REVOKE = "MANUAL_REVOKE",
  TOKEN_BLACKLISTED = "TOKEN_BLACKLISTED",
}
